Slide.create!([
  {id: 9, name: "past1", content: "<p>Es gibt viele Dinge, die Menschen schon immer getan haben.</p>\r\n<p>Zum Beispiel haben Menschen schon immer Kriege gegeneinander gef&uuml;hrt und andere Menschen zu Sklaven gemacht.</p>\r\n<p><strong>Doch bedeutet die Tatsache, dass Menschen fr&uuml;her andere Menschen zu Sklaven gemacht haben, dass es auch heute noch richtig ist, Menschen zu versklaven?</strong></p>", created_at: "2020-06-18 13:18:26", updated_at: "2020-06-18 21:37:39"},
  {id: 3, name: "go_vegan", content: "<h1>Go Vegan!</h1>\r\n<p>&nbsp;</p>\r\n<p>Falls du Hilfe brauchst, um vegan zu leben, dann bekommst du hier Unterst&uuml;tzung:</p>\r\n<p><a class=\"btn btn-info\" href=\"https://www.vegan-challenge.ch/\">www.vegan-challenge.ch</a></p>", created_at: "2020-06-17 20:02:51", updated_at: "2020-06-18 09:58:59"},
  {id: 5, name: "intelligence1", content: "<p>Wenn es okay ist, Tiere auszubeuten, weil sie weniger intelligent sind, ist es denn auch okay, andere Menschen auszubeuten, wenn sie weniger intelligent wie wir sind?</p>\r\n<p>Wir sind intelligenter als Kinder.</p>\r\n<p><strong>D&uuml;rfen wir deshalb Kinder ausbeuten? D&uuml;rfen wir Ihnen die H&auml;lse aufschneiden, sie zur Arbeit zwingen, sie einsperren und sie vergewaltigen?<br /></strong></p>\r\n<p>&nbsp;</p>", created_at: "2020-06-18 08:25:41", updated_at: "2020-06-18 18:43:16"},
  {id: 7, name: "intelligence2", content: "<p>Angenommen, es kommen Aliens auf die Erde, die um ein Vielfaches intelligenter als Menschen sind.</p>\r\n<p><strong>D&uuml;rfen diese Aliens uns Menschen ausbeuten?</strong></p>\r\n<p>&nbsp;</p>", created_at: "2020-06-18 10:42:27", updated_at: "2020-06-18 18:54:04"},
  {id: 1, name: "start", content: "<h1>Hallo! Ich bin Sandro!</h1>\r\n<p>&nbsp;</p>\r\n<p><strong>Ich denke, dass du vegan leben sollst.</strong></p>\r\n<p>Vegan zu leben bedeutet, keine tierischen Lebensmittel zu konsumieren, wie zum Beispiel Fleisch, Eier, Milch oder K&auml;se.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>M&ouml;chtest du wissen warum?</strong></p>\r\n<p>(Klick auf den Button unten!)</p>", created_at: "2020-06-17 19:10:46", updated_at: "2020-06-17 19:38:07"},
  {id: 6, name: "conflict_end", content: "<h1>Vielen Dank f&uuml;r das Gespr&auml;ch!</h1>\r\n<p>Du bist am Ende angelangt.</p>", created_at: "2020-06-18 09:57:17", updated_at: "2020-06-18 10:28:22"},
  {id: 8, name: "intelligence_dismissed", content: "<p>Wenn Aliens uns nicht ausbeuten d&uuml;rfen, obwohl sie viel intelligenter als wir sind, dann d&uuml;rfen wir Menschen gleichermassen auch Tiere nicht ausbeuten, auch wenn wir viel intelligenter als sie sind.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>Der Unterschied in Intelligenz rechtfertigt also nicht, Tiere auszubeuten.</strong></p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;</p>", created_at: "2020-06-18 11:23:30", updated_at: "2020-06-18 19:12:02"},
  {id: 4, name: "how", content: "<h1>Wie kann man die Ausbeutung von Tieren rechtfertigen?</h1>", created_at: "2020-06-17 20:07:52", updated_at: "2020-06-17 20:07:52"},
  {id: 2, name: "why", content: "<h1>Wer tierische Lebensmittel konsumiert, finanziert die Ausbeutung von Tieren.</h1>\r\n<p>Und die sieht so aus:</p>\r\n<div class=\"embed-responsive embed-responsive-16by9\" style=\"text-align: justify;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%;\" src=\"https://player.vimeo.com/video/334631596?muted=1&amp;autoplay=1&amp;loop=1&amp;title=0&amp;byline=0&amp;portrait=0\" frameborder=\"0\" allowfullscreen=\"\"></iframe></div>\r\n<p>&nbsp;</p>\r\n<p><strong>Kann man die Ausbeutung von Tieren rechtfertigen?</strong></p>", created_at: "2020-06-17 19:33:18", updated_at: "2020-06-17 20:12:14"},
  {id: 10, name: "past2", content: "<p>Nur weil Menschen fr&uuml;her etwas gemacht haben, heisst das noch lange nicht, dass es richtig war oder dass es auch heute richtig ist.</p>\r\n<p>Menschen haben fr&uuml;her viele Dinge aus verschiedenen Gr&uuml;nden getan. So mussten Menschen fr&uuml;her Tiere t&ouml;ten, um sich zu verteidigen, oder Tiere essen, um nicht zu verhungern.</p>\r\n<p>Aber das waren andere Zeiten, die man mit der heutigen Zeit nicht vergleichen kann. Heute laufen alle mit Smartphones rum, kaufen im Supermarkt nebenan ein, haben Strom und fliessendes Wasser zuhause, holen sich ein Bier aus dem K&uuml;hlschrank und schauen sich Netflix auf dem Tablet an.</p>\r\n<p>Niemand muss heute mehr Tiere essen, um nicht zu verhungern oder Tiere t&ouml;ten, um sich zu verteidigen.</p>\r\n<p><strong>Die Tatsache, dass Menschen fr&uuml;her etwas gemacht haben, rechtfertigt noch lange nicht, es heute auch zu machen.</strong></p>", created_at: "2020-06-18 20:23:46", updated_at: "2020-06-18 21:47:14"}
])

Option.create!([
  {content: "Warum?", target_slide: 2, slide_id: 1},
  {content: "Ja, ich kann die Ausbeutung von Tieren rechtfertigen", target_slide: 4, slide_id: 2},
  {content: "Nein, ich kann die Ausbeutung von Tieren nicht rechtfertigen", target_slide: 3, slide_id: 2},
  {content: "Wir dürfen Tiere ausbeuten, weil Tiere weniger intelligent als Menschen sind", target_slide: 5, slide_id: 4},
  {content: "Ja, ich finde, dass diese Aliens uns Menschen ausbeuten dürfen", target_slide: 6, slide_id: 7},
  {content: "Ich meine es anders: Der Mensch als Spezies ist hochintelligent und darf weniger intelligente Spezies ausbeuten", target_slide: 7, slide_id: 5},
  {content: "Ja, ich finde, dass wir Kinder und weniger intelligente Menschen ausbeuten dürfen", target_slide: 6, slide_id: 5},
  {content: "Nein, diese Aliens dürfen uns nicht ausbeuten", target_slide: 8, slide_id: 7},
  {content: "Weiter", target_slide: 4, slide_id: 8},
  {content: "Wir dürfen Tiere ausbeuten, weil wir das schon immer getan haben", target_slide: 9, slide_id: 4},
  {content: "Wir dürfen Tiere ausbeuten, weil Gott es uns erlaubt hat", target_slide: 4, slide_id: 4},
  {content: "Wir dürfen Tiere ausbeuten, so lange man sie freundlich und nett behandelt", target_slide: 4, slide_id: 4},
  {content: "Ja, ich finde, dass es auch heute noch richtig ist, Menschen zu versklaven", target_slide: 6, slide_id: 9},
  {content: "Nein, es ist falsch, Menschen zu versklaven, auch wenn das Menschen früher so gemacht haben.", target_slide: 10, slide_id: 9}
])
